version: '2'

services:
    harmony-php:
        container_name: harmony-php
        image: php:7.4-cli-alpine3.10
        volumes:
            - .:/var/www
        command: /bin/sh -c "cd /var/www; php vendor/bin/phpunit"
